### ISSUE TITLE
config.Fallback doesn't seem to work with config.DictOf

### ISSUE THREAD

**Issue by bradengroom** [reddit/baseplate#208]
```
>>> from baseplate import config
>>> raw_config1 = {
...   'foo': '12345',
... }
>>> raw_config2 = {
...   'foo.bar': '123',
...   'foo.baz': '567',
... }
>>> cfg1 = config.parse_config(raw_config1, {
...   "foo": config.Integer,
... })
>>> cfg1
{'foo': 12345}
>>> cfg2 = config.parse_config(raw_config2, {
...   "foo": config.DictOf(config.Integer),
... })
>>> cfg2
{'foo': {'bar': 123, 'baz': 567}}
>>> cfg3 = config.parse_config(raw_config2, {
...   "foo": config.Fallback(config.Integer, config.DictOf(config.Integer)),
... })
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python2.7/dist-packages/baseplate/config.py", line 540, in parse_config
    return parser.parse("", config)
  File "/usr/lib/python2.7/dist-packages/baseplate/config.py", line 411, in parse
    parsed[key] = parser.parse(key_path, raw_config)
  File "/usr/lib/python2.7/dist-packages/baseplate/config.py", line 427, in parse
    raise ConfigurationError(key_path, exc)
baseplate.config.ConfigurationError: foo: 'DictOf' object is not callable
>>> 
```

I tried implementing `__call__` myself:
```
class CallableDict(config.DictOf):
  def __call__(self, text):
    # TODO: call self.parse
```

but text just seemed to be an empty string when I dropped a debugger in `__call__`.

**Comment by spladug** [comment]
DictOf is pretty special/magical, this may be related to #159. Will look into it. Thanks for the detailed report!
